extends Node

@warning_ignore("unused_signal")
signal phase_changed(previous_phase: StringName, current_phase: StringName, wave_index: int)
@warning_ignore("unused_signal")
signal wave_started(wave_index: int, wave_id: StringName)
@warning_ignore("unused_signal")
signal wave_completed(wave_index: int, wave_id: StringName)
@warning_ignore("unused_signal")
signal enemy_spawned(enemy_id: StringName, instance_id: int, wave_index: int)
@warning_ignore("unused_signal")
signal enemy_died(enemy_id: StringName, instance_id: int, wave_index: int)

@warning_ignore("unused_signal")
signal player_health_changed(current: float, maximum: float)
@warning_ignore("unused_signal")
signal player_stamina_changed(current: float, maximum: float)
@warning_ignore("unused_signal")
signal hunger_changed(current: float, maximum: float)
@warning_ignore("unused_signal")
signal base_core_health_changed(current: float, maximum: float)

@warning_ignore("unused_signal")
signal inventory_changed(items: Dictionary)
@warning_ignore("unused_signal")
signal special_inventory_changed(items: Dictionary)
@warning_ignore("unused_signal")
signal inventory_selection_changed(slot_index: int)
@warning_ignore("unused_signal")
signal watch_item_use_requested(item_id: StringName)
@warning_ignore("unused_signal")
signal held_item_changed(item_id: StringName)
@warning_ignore("unused_signal")
signal item_use_progress(item_id: StringName, progress: float, active: bool)
@warning_ignore("unused_signal")
signal resource_looted(resource_id: StringName, payload: Dictionary)
@warning_ignore("unused_signal")
signal loot_container_opened(container_id: StringName, payload: Dictionary)
@warning_ignore("unused_signal")
signal world_item_picked_up(item_id: StringName, quantity: int)
@warning_ignore("unused_signal")
signal item_used(item_id: StringName, quantity: int)
@warning_ignore("unused_signal")
signal interaction_prompt_changed(prompt: String)
@warning_ignore("unused_signal")
signal debug_test_notice(message: String, category: StringName)
@warning_ignore("unused_signal")
signal combat_feedback(message: String, tone: StringName)
@warning_ignore("unused_signal")
signal player_perk_selected(perk_id: StringName)
@warning_ignore("unused_signal")
signal player_active_skill_changed(skill_id: StringName, cooldown_remaining: float, charges: int)
@warning_ignore("unused_signal")
signal player_active_skill_triggered(skill_id: StringName)
@warning_ignore("unused_signal")
signal player_action_blocked(action_id: StringName, reason_id: StringName)
@warning_ignore("unused_signal")
signal watch_state_changed(active: bool)
@warning_ignore("unused_signal")
signal wave_timer_changed(remaining_seconds: float, total_seconds: float, wave_index: int)
@warning_ignore("unused_signal")
signal player_died(reason: StringName)
@warning_ignore("unused_signal")
signal player_weapon_changed(weapon_id: StringName)
@warning_ignore("unused_signal")
signal player_ammo_changed(current: int, reserve: int)
@warning_ignore("unused_signal")
signal player_noise_emitted(position: Vector3, radius: float, noise_id: StringName)

@warning_ignore("unused_signal")
signal combat_hit(data: DamageEventData)
@warning_ignore("unused_signal")
signal damage_resolved(result: DamageResolutionData)
@warning_ignore("unused_signal")
signal status_applied(target_id: int, status_id: StringName)
@warning_ignore("unused_signal")
signal status_removed(target_id: int, status_id: StringName)
@warning_ignore("unused_signal")
signal status_list_changed(target_id: int, statuses: Array[Dictionary])
@warning_ignore("unused_signal")
signal status_rejected(target_id: int, status_id: StringName, reason_id: StringName)

@warning_ignore("unused_signal")
signal run_started(run_id: StringName)
@warning_ignore("unused_signal")
signal run_failed(reason: StringName)
@warning_ignore("unused_signal")
signal run_completed(ending_id: StringName)
@warning_ignore("unused_signal")
signal save_requested(slot_id: StringName)
