extends Node

@warning_ignore("unused_signal")
signal phase_changed(previous_phase: StringName, current_phase: StringName, wave_index: int)
@warning_ignore("unused_signal")
signal wave_started(wave_index: int, wave_id: StringName)
@warning_ignore("unused_signal")
signal wave_completed(wave_index: int, wave_id: StringName)

@warning_ignore("unused_signal")
signal player_health_changed(current: float, maximum: float)
@warning_ignore("unused_signal")
signal player_stamina_changed(current: float, maximum: float)
@warning_ignore("unused_signal")
signal hunger_changed(current: float, maximum: float)
@warning_ignore("unused_signal")
signal base_core_health_changed(current: float, maximum: float)

@warning_ignore("unused_signal")
signal inventory_changed(items: Dictionary)
@warning_ignore("unused_signal")
signal resource_looted(resource_id: StringName, payload: Dictionary)
@warning_ignore("unused_signal")
signal interaction_prompt_changed(prompt: String)
@warning_ignore("unused_signal")
signal debug_test_notice(message: String, category: StringName)
@warning_ignore("unused_signal")
signal watch_state_changed(active: bool)
@warning_ignore("unused_signal")
signal wave_timer_changed(remaining_seconds: float, total_seconds: float, wave_index: int)
@warning_ignore("unused_signal")
signal player_died(reason: StringName)
@warning_ignore("unused_signal")
signal player_weapon_changed(weapon_id: StringName)
@warning_ignore("unused_signal")
signal player_ammo_changed(current: int, reserve: int)
@warning_ignore("unused_signal")
signal player_noise_emitted(position: Vector3, radius: float, noise_id: StringName)

@warning_ignore("unused_signal")
signal combat_hit(data: DamageEventData)
@warning_ignore("unused_signal")
signal status_applied(target_id: int, status_id: StringName)
@warning_ignore("unused_signal")
signal status_removed(target_id: int, status_id: StringName)

@warning_ignore("unused_signal")
signal run_started(run_id: StringName)
@warning_ignore("unused_signal")
signal run_failed(reason: StringName)
@warning_ignore("unused_signal")
signal run_completed(ending_id: StringName)
@warning_ignore("unused_signal")
signal save_requested(slot_id: StringName)
